project:
  type: book

book:
  title: "Global NCP: Two-Path Analysis Structure"
  author: "Jerónimo Rodríguez Escobar"
  date: last-modified
  chapters:
    - index.qmd
    - docs/methodology.md
    - analysis/prepare_data.qmd
    - analysis/process_data.qmd
    - analysis/LC_change.qmd
    - analysis/hotspot_extraction.qmd
    - analysis/hotspot_synthesis.qmd
    - analysis/KS_tests_hotspots.qmd
    - analysis/results_interpretation.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  pdf:
    documentclass: scrreprt

execute:
  echo: false
  warning: false
  message: false
