name: geopy311
channels:
  - conda-forge
dependencies:
  - gdal=3.10.3
  - geopandas
  - rtree=1.4.0
  - scipy=1.15.2
  - shapely=2.1.0
  - numpy=2.2.5
  - numexpr=2.10.2
  - psutil=7.0.0
  - cython=3.0.11
  - exactextract=0.2.2
  - retrying=1.3.4