name: geopy311
channels:
  - conda-forge
dependencies:
  - cython=3.0.11
  - exactextract=0.2.2
  - gdal=3.10.3
  - geopandas=1.0.1
  - numexpr=2.10.2
  - numpy=2.2.5
  - psutil=7.0.0
  - pyyaml=6.0.2
  - rasterio=1.4.3
  - retrying=1.3.4
  - rtree=1.4.0
  - scipy=1.15.2
  - shapely=2.1.0
