---
title: "Tasks Jerónimo"
author: "Jeronimo Rodriguez-Escobar"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pending tasks

Here, a synthesis of the tasks pending for this week in terms of priority, current status, available data, and next steps - suggestions


## NBS Mapping

### Create Map outputs with the prioritized Ecosystem Services for the 5 regions:

- Mata Atlántica (Brazil)
- Diana Northen (Madagascar)
- Península de Yucatán (México)
- Made de Dios (Perú)
- Central Amannites (Vietnam)



# I need to piut all this in a single place and remember what thefuck is the data 

Order: 
1. Land Cover Maps
2. Protected Areas
3. Restoration Areas

4. Water Based Services. 
 - Conservation
 - Restoration
 -  Density Plots
 
5. Access/Beneficiaries
 - Conservation
 - Restoration
 - Density Plots
 
 6. Coastal Protection with a 2 km buffer from the coastline
 - Conservation
 - Restoration
 - Density Plots
 

Current Versions of the maps in Google Drive. Stored as pdf, but can be exported as individual images if necessary.-> conveet into standalone images and add to a ppt. 
-First page:  Sediment and Nitrogen retention, pollination service (in terms of people fed), with conservation and restoration side by side (what about a BAU scenario?)
-Second page: Includes downstream Beneficiaries access conservation and restoration
-Third page: coastal rosk reduction: general view of the area with population < 10m and service provision (point vector value, Service: Rt_nohab - Rt). The insets have closeups to areas I found interesting (visually). Here, instead of the vector file, we are using the raster with the service.
-Fourth page: Reclassified ESA land cover map 2020. I have the reclassification matrix stored if necessary.


Final chart: Share of PA/RA as total of the area (need to reclassify the LC map into a background to fill with zeros), only one column. 

### Distribution of the ecosystems services inside and outside of the protected areas

Produced barplots that compare side by side the proportion of the total area (in terms of the valid pixels) that correpsonds to the protected areas (Cats )

Creates density plots to compare the provision of each ecosystem service inside and 

