study_areas:
  Brazil:
    name: "Espírito Santo"
    intervention_area: 30200  # in hectares
    restoration_file: "BRAZIL_ES_msk.tif"
  Mexico:
    name: "Yucatán Peninsula"
    intervention_area: 15000
    restoration_file: "MEXICO_ES_msk.tif"
  Peru:
    name: "Madre de Dios"
    intervention_area: null  # Placeholder for future
    restoration_file: null
  Madagascar:
    name: "Madagascar"
    intervention_area: null  # Placeholder for future
    restoration_file: null
  Vietnam:
    name: "Vietnam"
    intervention_area: null  # Placeholder for future
    restoration_file: null
