---
title: "Calculate Services"
output: html_notebook
---

Here, I prepare the new rasters wit the potential and other variable.

## **1. Compute Differences**



```{r get differences, eval=FALSE, include=FALSE}

# Define service names and colors
service <- rep(c("Coastal_Protection", "Nitrogen_Export", "Sediment_Export", "Usle", "Nature_Access", "Pollination"), each=2)
year <- rep(c(1992,2020), 6)
filename <- as_tibble(cbind(service, raster_name, year))


outpath <- here("input_ES")
m_index <- length(rasters_list) %/% 2
lab <- unique(service)
lab <- gsub(" ", "_", lab)


l1 <- rasters_list[seq(1,length(rasters_list), by=2)]
l2 <- rasters_list[seq(2,length(rasters_list), by=2)]

diffs <- map2(l2, l1, ~ .x - .y)

# Export difference rasters
map(1:length(diffs), function(x) writeRaster(diffs[[x]], paste0(outpath, "/change_calc/", lab[x], '_diff.tif'),overwrite=TRUE))
```



## 2.  Prepare Potential of Sed retention data.

```{r getpotential Sed retention , eval=FALSE, include=FALSE}
inpath <- here("input_ES", "Pot_Sed_retention")
tiffes <- file.path(inpath, list.files(paste0(inpath),pattern= 'tif$'))
filename<- basename(tiffes)
# Use terra::rast() to load each file as a SpatRaster object


rasters_list <- lapply(tiffes, rast)
rcl <- matrix(c(
  -Inf, 0, NA   # Any value from 0 to Infinity becomes 1
), ncol = 3, byrow = TRUE)

rasters_list <- lapply(rasters_list, function(r){
  r <- classify(r,rcl, right=FALSE)
},mc.cores = num.cores))



m_index <- length(rasters_list) %/% 2
#lab <- unique(service)
l1 <- rasters_list[seq(1,length(rasters_list), by=2)]
l2 <- rasters_list[seq(2,length(rasters_list), by=2)]
 # test with future_map2 next time to get this to run faster. 

pot_SedRet1 <- (l1[[2]]-l1[[1]])/l1[[2]]


pot_SedRet2 <- (l2[[2]]-l2[[1]])/l2[[2]]

psr_92 <- classify(pot_SedRet1,rcl, right=FALSE)
psr_20 <- classify(pot_SedRet2,rcl, right=FALSE)

writeRaster(psr_92, paste0(inpath, '/', 'pot_SedRet_92.tif'), overwrite=TRUE)
writeRaster(psr_20, paste0(inpath, '/', 'pot_SedRet_20.tif'), overwrite=TRUE)
diff <- psr_92 - psr_20
writeRaster(diff, paste0(inpath, '/', 'pot_Sed_r_diff.tif'), overwrite)

```

