#' Compare Zonal Statistics Outputs (INI vs YAML Pipelines)
#'
#' This function loads the CSV generated by the `zonal_stats_toolkit` (INI)
#' and the aggregated CSV from `summary_pipeline_landgrid.py` (YAML), joins them
#' by the specified grouping column, and compares the Means and Sums.
#'
#' @param ini_csv Path to the CSV from zonal_stats_toolkit
#' @param yaml_csv Path to the CSV from aggregate_yaml_outputs.py
#' @param group_col The column name to join on (e.g., "region_wb", "WWF_biome")
#' @export
compare_pipelines <- function(ini_csv, yaml_csv, group_col) {
  message("Loading INI output: ", ini_csv)
  ini_data <- read.csv(ini_csv)

  message("Loading YAML output: ", yaml_csv)
  yaml_data <- read.csv(yaml_csv)

  # Dictionary mapping the YAML layer ID to the INI raster stem
  services <- list(
    "nature_access_diff"        = "nature_access_diff_1992_2020",
    "n_ret_ratio_diff"          = "n_retention_ratio_diff_1992_2020",
    "sed_ret_ratio_diff"        = "sed_retention_ratio_diff_1992_2020",
    "n_export_diff"             = "n_export_diff_1992_2020",
    "n_retention_diff"          = "n_retention_diff_1992_2020",
    "sed_export_diff"           = "sed_export_diff_1992_2020",
    "realized_pollination_diff" = "realized_pollination_on_ag_1992_2020_diff"
  )

  # Join the datasets on the grouping column
  comparison <- dplyr::inner_join(
    ini_data,
    yaml_data,
    by = group_col,
    suffix = c("_INI", "_YAML")
  )

  message("Joined ", nrow(comparison), " regions.")

  summary_rows <- list()

  for (yaml_base in names(services)) {
    ini_base <- services[[yaml_base]]

    # Construct column names
    ini_mean_col  <- paste0("mean_", ini_base)
    yaml_mean_col <- paste0(yaml_base, "_true_mean")

    ini_sum_col   <- paste0("sum_", ini_base)
    yaml_sum_col  <- paste0(yaml_base, "_sum")

    if (ini_mean_col %in% names(comparison) && yaml_mean_col %in% names(comparison)) {
      abs_diff <- abs(comparison[[ini_mean_col]] - comparison[[yaml_mean_col]])
      rel_err <- abs_diff / pmax(abs(comparison[[ini_mean_col]]), 1e-9) # avoid division by zero

      summary_rows[[length(summary_rows) + 1]] <- data.frame(
        Service = yaml_base,
        Stat = "Mean",
        Max_Abs_Diff = max(abs_diff, na.rm = TRUE),
        Max_Rel_Err_Pct = max(rel_err, na.rm = TRUE) * 100
      )
    }

    if (ini_sum_col %in% names(comparison) && yaml_sum_col %in% names(comparison)) {
      abs_diff <- abs(comparison[[ini_sum_col]] - comparison[[yaml_sum_col]])
      rel_err <- abs_diff / pmax(abs(comparison[[ini_sum_col]]), 1e-9)

      summary_rows[[length(summary_rows) + 1]] <- data.frame(
        Service = yaml_base,
        Stat = "Sum",
        Max_Abs_Diff = max(abs_diff, na.rm = TRUE),
        Max_Rel_Err_Pct = max(rel_err, na.rm = TRUE) * 100
      )
    }
  }

  res_df <- do.call(rbind, summary_rows)
  print(knitr::kable(res_df, digits = 4))

  tolerance_pct <- 1.0 # 1% tolerance for fractional vs rasterized border logic
  if (any(res_df$Max_Rel_Err_Pct > tolerance_pct, na.rm = TRUE)) {
    message("\nWARNING: Some differences exceed the ", tolerance_pct, "% relative error tolerance. Methodological divergence detected!")
  } else {
    message("\nSUCCESS: Both pipelines produced highly similar results (within ", tolerance_pct, "% tolerance)!")
  }

  return(invisible(comparison))
}