# Example config file for the globalNCP summary pipeline

workspace_dir:
  path: "./summary_pipeline_workspace"

vector_zones:
  10k_grid_access: 
    path: "../data/reference/grid_land_only.shp"

raster_layers:
  nature_access_lspop2019_ESA1992:
    path: "../data/Spring/Change/nature_access_lspop2019_ESA_1992_2020_diff.tif"
    band: 1
op_stats:
  - mean
  
