# Example config file for the globalNCP summary pipeline

workspace_dir:
  path: "./summary_pipeline_workspace"

vector_zones:
  ghydrosheds_lv6: 
    path: "../data/reference/hydrosheds_lv6_synth.gpkg"

raster_layers:
  global_usle_marine_mod_ESA_1992:
    path: "../data/Spring/Inspring/global_usle_marine_mod_ESA_1992_compressed_md5_7e68e0.tif"
    band: 1
  global_usle_marine_mod_ESA_2020:
    path: "../data/Spring/Inspring/global_usle_marine_mod_ESA_2020_compressed_md5_99e715.tif"
    band: 1
  nature_access_lspop2019_ESA1992:
    path: "../data/Spring/Inspring/nature_access_lspop2019_ESA1992_md5_b32b8b.tif"
    band: 1
  nature_access_lspop2019_ESA2020:
    path: "../data/Spring/Inspring/nature_access_lspop2019_ESA2020_compressed_md5_6727ac.tif"
    band: 1
  N_ret_ratio_1992:
    path: "../data/Spring/Inspring/N_ret_ratio_1992.tif"
    band: 1
  N_ret_ratio_2020:
    path: "../data/Spring/Inspring/N_ret_ratio_2020.tif"
    band: 1
  Sed_ret_ratio_1992:
    path: "../data/Spring/Inspring/Sed_ret_ratio_1992.tif"
    band: 1 
  Sed_ret_ratio_2020:
    path: "../data/Spring/Inspring/Sed_ret_ratio_2020.tif"
    band: 1 



op_stats:
  - mean
  
