service_labels:
  sed_export: "Sed_export"
  n_export: "N_export"
  n_retention: "N_retention"
  nature_access: "Nature_Access"
  pollination: "Pollination"
  usle: "USLE"
  n_ret_ratio: "N_Ret_Ratio"
  sed_ret_ratio: "Sed_Ret_Ratio"
  Rt_ratio: "C_Risk_Red_Ratio"
  Rt: "C_Risk"
  Rt_service: "C_Prot_service"

drop_services:
  - Rt_nohab

loss_services:        # decreases desirable
  - Nature_Access
  - Pollination
  - N_Ret_Ratio
  - Sed_Ret_Ratio
  - C_Risk_Red_Ratio

gain_services:        # increases undesirable/damage
  - Sed_export
  - N_export
  - C_Risk
