socio_vars:
  GHS_BUILT_S_E2020_mean: "Built Area"
  fields_mehrabi_2017_mean: "Field Size"
  hdi_raster_predictions_2020_mean: "HDI"
  rast_adm1_gini_disp_2020_mean: "Income Inequality"
  rast_gdpTot_1990_2020_30arcsec_2020_sum: "GDP (Total)"
  GHS_POP_E2020_GLOBE_sum: "Population (GHS)"
  GlobPOP_Count_30arc_2020_sum: "Population (Global)"

transforms:
  default: auto
  overrides:
    rast_gdpTot_1990_2020_30arcsec_2020_sum: log1p
    GHS_POP_E2020_GLOBE_sum: log1p
    GlobPOP_Count_30arc_2020_sum: log1p
