# ==============================================================================
# Global Land Cover Change Driver Hotspots Map (v2 - Nuanced Transitions)
# 
# OVERVIEW:
# This script generates a global map visualizing the primary hotspots of direct
# land cover conversion. It identifies the top 5% of 10km grid cells
# experiencing the most intense change for several key drivers (e.g., Forest
# Loss, Cropland Expansion, Grassland Loss) and maps them categorically.
#
# --- NOTE FOR BECKY (Transition to Nuanced Drivers) ---
# The previous version of this map used a generic "Multiple Overlapping Drivers"
# category. This was not very informative for understanding the actual land
# transition processes happening on the ground.
#
# This updated version refines the classification logic to identify specific,
# policy-relevant driver combinations. Instead of a generic "multiple", we now
# explicitly map critical transitions like:
#   - "Deforestation for Cropland" (Forest Loss + Cropland Expansion)
#   - "Savannization / Pasture" (Forest Loss + Grassland Gain)
#   - "Grassland to Cropland" (Grassland Loss + Cropland Expansion)
#
# The previous version of this map used a generic "Multiple Overlapping Drivers"
# category. This was not very informative for understanding the actual land
# transition processes happening on the ground.
#
# This updated version refines the classification logic to identify specific,
# policy-relevant driver combinations. Instead of a generic "multiple", we now
# explicitly map critical transitions like:
#   - "Deforestation for Cropland" (Forest Loss + Cropland Expansion)
#   - "Savannization / Pasture" (Forest Loss + Grassland Gain)
#   - "Grassland to Cropland" (Grassland Loss + Cropland Expansion)
#
# This gives us a much richer map that tells a clearer story about the pathways
# of land conversion. Let me know what you think of this approach.
# ---
#
# --- METHODOLOGICAL NOTE ON INTERPRETATION ---
# It is critical to understand what the hotspot metric represents. The underlying
# values (e.g., `ForestLoss_Loss_Forest_1992_2020`) are calculated as a
# percentage of the *total 10km grid cell area*.
#
# This means a hotspot of "10% Forest Loss" could represent a cell that was 10%
# forested and lost all of it, or a cell that was 90% forested and lost ~11% of
# its forest. The map therefore shows hotspots of *landscape transformation
# intensity*, not change relative to the initial cover type's area within the cell.
# This is a key distinction for interpretation and future discussion.
# ---
#
# WORKFLOW:
# 1.  Loads the pre-calculated global LCC driver hotspot data from
#     `processed/hotspots/drivers_by_group/pct/global/hotspots_global_pct.gpkg`.
#     This file is generated by `analysis/hotspot_extraction.qmd`.
# 2.  Classifies each hotspot cell into a primary driver category. The logic
#     prioritizes the specific combinations listed above before falling back to
#     single drivers or a generic "Multiple Overlapping Drivers" for other combos.
# 3.  Generates and saves a global map to `outputs/plots/maps/`.
#
# ==============================================================================

library(sf)
library(ggplot2)
library(dplyr)
library(stringr)
library(here)

source(here("R", "paths.R"))

# Path to the global LCC driver hotspots layer (consolidated)
gpkg_path <- file.path(data_dir(), "processed", "hotspots", "drivers_by_group", "pct", "global", "hotspots_global_pct.gpkg")

message("Reading global LCC driver hotspots file...")
if (!file.exists(gpkg_path)) {
  stop("Driver GPKG not found: ", gpkg_path)
}
sf_data <- st_read(gpkg_path, quiet = TRUE)

message("Fixing dateline wraparound artifacts in memory...")
sf_data <- st_wrap_dateline(sf_data, options = c("WRAPDATELINE=YES", "DATELINEOFFSET=180"))

message("Transforming to Equal Earth projection (EPSG:8857)...")
sf_data <- st_transform(sf_data, crs = "EPSG:8857")

message("Reading and transforming base map...")
base_map_path <- "/home/jeronimo/data/global_ncp/vector_basedata/cartographic_ee_r264_correspondence.gpkg"
base_sf <- st_read(base_map_path, quiet = TRUE)
base_sf <- st_transform(base_sf, crs = "EPSG:8857")

# Create a clean categorical variable for the map based on the hotspot_services string
sf_data <- sf_data %>%
  mutate(
    hotspot_count = as.numeric(hotspot_count),
    hotspot_services = coalesce(hotspot_services, ""),
    Driver = case_when(
      # Specific, policy-relevant combinations first
      str_detect(hotspot_services, "Forest_Loss") & str_detect(hotspot_services, "Crop_Exp") ~ "Deforestation for Cropland",
      str_detect(hotspot_services, "Forest_Loss") & str_detect(hotspot_services, "Grassland_Gain") ~ "Savannization / Pasture",
      str_detect(hotspot_services, "Grassland_Loss") & str_detect(hotspot_services, "Crop_Exp") ~ "Grassland to Cropland",
      # If more than one driver but not a special case, use the generic multiple
      hotspot_count > 1 ~ "Multiple Overlapping Drivers",
      # General, single drivers next
      str_detect(hotspot_services, "Forest_Loss") ~ "Forest Loss",
      str_detect(hotspot_services, "Grassland_Gain") ~ "Grassland Expansion",
      str_detect(hotspot_services, "Grassland_Loss") ~ "Grassland Loss",
      str_detect(hotspot_services, "Crop_Exp") ~ "Cropland Expansion",
      str_detect(hotspot_services, "Urban_Exp") ~ "Urban Expansion",
      TRUE ~ "Other"
    ),
    Driver = factor(Driver, levels = c("Deforestation for Cropland", "Savannization / Pasture", "Grassland to Cropland", "Forest Loss", "Grassland Loss", "Grassland Expansion", "Cropland Expansion", "Urban Expansion", "Multiple Overlapping Drivers", "Other"))
  )

message("Generating categorical map...")

# Define custom semantic colors
driver_colors <- c(
  "Deforestation for Cropland" = "#b15928",   # Brown
  "Savannization / Pasture" = "#ffff99",      # Light Yellow
  "Grassland to Cropland" = "#cc4c02",        # More distinct Dark Orange
  "Forest Loss" = "#2ca25f",                  # Forest Green (for standalone loss)
  "Grassland Expansion" = "#a6d854",          # Light green
  "Grassland Loss" = "#fdbf6f",               # Sandy yellow/brown (for standalone loss)
  "Cropland Expansion" = "#e69138",           # Agricultural Orange (for standalone expansion)
  "Urban Expansion" = "#e41a1c",              # Built-up Red
  "Multiple Overlapping Drivers" = "#984ea3", # Purple (for other overlaps)
  "Other" = "gray50"
)

p <- ggplot() +
  # Base map underneath
  geom_sf(data = base_sf, fill = "gray95", color = "gray80", linewidth = 0.1) +
  # color = NA ensures the grid cell borders do not render, preventing visual clutter
  geom_sf(data = sf_data, aes(fill = Driver), color = NA) +
  scale_fill_manual(values = driver_colors, name = "Primary Land Conversion Driver\n(Top 5% Most Intense)") +
  labs(
    title = "Hotspots of Direct Land Cover Conversion (1992 - 2020)",
    subtitle = "Locations experiencing the most intense physical landscape transformation"
  ) +
  theme_void() +
  theme(
    plot.title = element_text(size = 20, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 14, hjust = 0.5, margin = margin(b = 15)),
    legend.position = "bottom",
    legend.title = element_text(size = 14, face = "bold"),
    legend.text = element_text(size = 12),
    legend.key.size = unit(1, "cm")
  ) +
  guides(fill = guide_legend(ncol = 4, byrow = TRUE))

out_dir <- here("outputs", "plots", "maps")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
out_path <- file.path(out_dir, "global_lcc_driver_map.png")

message("Saving map to: ", out_path)
ggsave(out_path, p, width = 16, height = 9, bg = "white", dpi = 600)

# --- Summary Table ---
message("Calculating summary of driver categories...")

driver_summary <- sf_data %>%
  st_drop_geometry() %>%
  count(Driver, name = "Hotspot_Cell_Count") %>%
  mutate(
    Percentage_of_Total = (Hotspot_Cell_Count / sum(Hotspot_Cell_Count)) * 100
  ) %>%
  arrange(desc(Hotspot_Cell_Count))

print(driver_summary)