# ==============================================================================
# 10km-Native Change Figure: Paired Export/Retention Rows
# ==============================================================================
#
# Phase 5.1 + 5.2 of the hotspot redesign (docs/hotspot_redesign_plan.md).
#
# Phase 5.1: replaces the dissolved-by-WWF_biome-name "biome" change map
# (outputs/maps/map_biome_{pct,abs}.png, generated by make_faceted_maps.R
# from a biome-dissolved gpkg built in the sibling zonal_stats_toolkit repo)
# with a map plotted directly off the native 10km grid. Dissolving by biome
# NAME merges every landlocked instance of a biome (e.g. Mongolia's Gobi)
# with every coastal instance of that same biome worldwide (Atacama, Namib)
# into one polygon with one blended value -- a real representational
# limitation, confirmed non-bug (see WORKLOG 2026-07-29). Plotting the native
# grid cell-by-cell instead of a dissolved polygon avoids this entirely.
#
# Phase 5.2: restructures the panel layout into paired rows -- export next to
# its corresponding retention/reduction ratio for each of the 3 services that
# have one (Nitrogen, Sediment, Coastal), ordered nitrogen -> sediment ->
# coastal -> pollination -> nature access. Pollination and Nature Access have
# no retention-ratio analog (confirmed: no such column was ever modeled for
# either) so they aren't an export/retention pair, but share the 4th row
# together (per Becky's suggestion) rather than each getting a full row to
# itself -- a 4-row, not 5-row, figure.
#
# NOTE: retention/reduction-ratio columns are shown here for context even
# though they were DROPPED from the 5-service hotspot *definition* in this
# redesign -- this figure characterizes raw magnitude of change across all 8
# originally-modeled services, a different purpose from the hotspot maps.
#
# Deliberately NOT wired into paper_draft.qmd or the book chapters yet (per
# standing instruction to leave the paper alone until the redesign settles)
# -- output filenames are new (map_native10km_*), not a silent overwrite of
# map_biome_*.png, so the old biome-dissolved map remains available
# unchanged for comparison until Becky/the paper text is ready to switch.
#
# Performance note: an initial vector geom_sf render of one full-grid panel
# (1.37M cells after Antarctica/Seven-seas/Lakes/Rock&Ice exclusion) took
# ~145s. Rasterizing each column to 10km (terra::rasterize, matching the
# resolution gdal_rasterize_hotspots.sh already uses for Rich's deliverables)
# and plotting via geom_tile cut that to ~15s/panel after a one-time ~65s
# load/filter/transform -- confirmed visually identical output, ~5x faster
# for the full 16-panel (8 services x pct/abs) run.
# ==============================================================================

library(sf)
library(terra)
library(ggplot2)
library(dplyr)
library(patchwork)
library(here)

source(here("R", "paths.R"))

out_dir <- here("outputs", "maps")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

# ------------------------------------------------------------------------------
# 1. Direction + color scale (same colorblind-safe orange/teal convention as
#    make_faceted_maps.R -- see that file's Rule 2 comment / WORKLOG for why
#    literal red/green was not used despite Becky's original request).
# ------------------------------------------------------------------------------

goods <- c("Pollination", "Nature_Access", "N_Ret_Ratio", "Sed_Ret_Ratio", "C_Risk_Red_Ratio")
damages <- c("N_export", "Sed_export", "C_Risk")

get_direction <- function(service) if (service %in% goods) "good" else "damage"

get_color_scale <- function(service, limits) {
  if (get_direction(service) == "good") {
    scale_fill_gradient2(low = "#F07D00", mid = "white", high = "#009191",
                          midpoint = 0, name = "Change", na.value = "gray90", limits = limits)
  } else {
    scale_fill_gradient2(low = "#009191", mid = "white", high = "#F07D00",
                          midpoint = 0, name = "Change", na.value = "gray90", limits = limits)
  }
}

# Nitrogen -> Sediment -> Coastal -> Pollination -> Nature Access, paired
# export/retention where a pairing exists (see header note).
panel_defs <- list(
  list(service = "N_export",         col_pct = "n_export_pct_chg",         col_abs = "n_export_abs_chg"),
  list(service = "N_Ret_Ratio",      col_pct = "n_ret_ratio_pct_chg",      col_abs = "n_ret_ratio_abs_chg"),
  list(service = "Sed_export",       col_pct = "sed_export_pct_chg",       col_abs = "sed_export_abs_chg"),
  list(service = "Sed_Ret_Ratio",    col_pct = "sed_ret_ratio_pct_chg",    col_abs = "sed_ret_ratio_abs_chg"),
  list(service = "C_Risk",           col_pct = "c_risk_pct_chg",           col_abs = "c_risk_abs_chg"),
  list(service = "C_Risk_Red_Ratio", col_pct = "c_risk_red_ratio_pct_chg", col_abs = "c_risk_red_ratio_abs_chg"),
  list(service = "Pollination",      col_pct = "pollination_pct_chg",      col_abs = "pollination_abs_chg"),
  list(service = "Nature_Access",    col_pct = "nature_access_pct_chg",    col_abs = "nature_access_abs_chg")
)

# Pollination and Nature Access share the 4th row (per Becky's own layout
# suggestion) rather than each getting a full row with an empty spacer --
# neither has a retention analog, so they're not an export/retention pair,
# just sharing space for a more compact figure.
row_pairs <- list(
  c("N_export", "N_Ret_Ratio"),
  c("Sed_export", "Sed_Ret_Ratio"),
  c("C_Risk", "C_Risk_Red_Ratio"),
  c("Pollination", "Nature_Access")
)

# ------------------------------------------------------------------------------
# 2. Load, filter, and reproject the native grid ONCE -- reused across all
#    16 panels (8 services x pct/abs) to amortize the one-time cost.
# ------------------------------------------------------------------------------

message("Loading 10k_change_calc.gpkg...")
needed_cols <- c("grid_fid", "continent", "WWF_biome",
                  unlist(lapply(panel_defs, function(d) c(d$col_pct, d$col_abs))))
grid <- st_read(here("data", "processed", "10k_change_calc.gpkg"), quiet = TRUE)
grid <- grid[, intersect(names(grid), c(needed_cols, "geom", "geometry"))]

# Same Antarctica/Seven-seas/Lakes/Rock&Ice exclusion used throughout this
# analysis (scripts/extract_hotspots_5service.R) -- 1,372,447 cells remain.
grid <- grid %>%
  filter(!continent %in% c("Antarctica", "Seven seas (open ocean)"),
         !WWF_biome %in% c("Lakes", "Rock & Ice"))
message("  -> ", nrow(grid), " cells after exclusion")

grid <- st_transform(grid, "EPSG:8857")
vect_grid <- vect(grid)
r_template <- rast(vect_grid, resolution = 10000)

# Basemap: same custom cartographic base layer make_5service_overlap_maps.R
# uses, so sparse-data services (Coastal Risk: 80,040 of 1,522,073 cells --
# a narrow shoreline-only phenomenon, confirmed not a bug) render as visible
# coastal detail against gray landmass instead of near-blank whitespace that
# looks broken.
base_map_path <- file.path(data_dir(), "vector_basedata", "cartographic_ee_r264_correspondence.gpkg")
base_sf <- st_read(base_map_path, quiet = TRUE) %>% st_transform("EPSG:8857")

panel_dpi <- 150  # native: r_template is ncol x nrow px at this size -> 1:1 pixel mapping, no up/downsampling
panel_width_in <- dim(r_template)[2] / panel_dpi
panel_height_in <- dim(r_template)[1] / panel_dpi

panels_dir <- file.path(out_dir, "native10km_panels")
dir.create(panels_dir, recursive = TRUE, showWarnings = FALSE)

# ------------------------------------------------------------------------------
# 3. Per-service, per-metric color limits (1st/99th percentile), computed
#    directly from the single already-loaded file -- simpler than
#    make_faceted_maps.R's compute_service_limits(), which pooled across 3
#    separate grouping gpkgs; here there is only one source file.
# ------------------------------------------------------------------------------

compute_limits <- function(val_vec) {
  q <- quantile(val_vec, c(0.01, 0.99), na.rm = TRUE)
  lim <- max(abs(q))
  c(-lim, lim)
}

# ------------------------------------------------------------------------------
# 4. Rasterize + plot one panel
# ------------------------------------------------------------------------------

make_panel <- function(col_name, service_name, metric, title_size = 10, legend_key_width_cm = 1) {
  limits <- compute_limits(grid[[col_name]])

  r <- terra::rasterize(vect_grid, r_template, field = col_name)
  df_r <- as.data.frame(r, xy = TRUE)
  names(df_r)[3] <- "value"
  # Clip outliers to the 1st/99th-percentile limits post-rasterize, same
  # effect as clipping the source vector but without mutating the shared
  # vect_grid object (reused across all 16 panels). terra::as.data.frame()
  # drops NA cells by default, so only cells with real data reach geom_tile
  # -- the basemap shows through everywhere there's no data at all.
  df_r$value <- pmax(pmin(df_r$value, limits[2]), limits[1])

  # Same fix as make_paper_supplement_maps.py's fade-to-transparent: near-zero
  # ("no meaningful change") cells were rendering as opaque near-white, which
  # covers the gray basemap just as completely as a real color would -- the
  # basemap fix alone doesn't help if every land cell paints over it anyway.
  # Fade alpha toward 0 within 8% of the symmetric limit so only cells with a
  # real change stay opaque; true no-data cells are already absent from df_r.
  fade_threshold <- max(0.08 * limits[2], 1e-9)
  df_r$alpha <- pmin(abs(df_r$value) / fade_threshold, 1)

  p <- ggplot() +
    geom_sf(data = base_sf, fill = "gray95", color = "gray80", linewidth = 0.1) +
    geom_tile(data = df_r, aes(x = x, y = y, fill = value, alpha = alpha)) +
    scale_alpha_identity(guide = "none") +
    get_color_scale(service_name, limits) +
    coord_sf(crs = "EPSG:8857") +
    labs(title = gsub("_", " ", service_name)) +
    theme_void() +
    theme(
      plot.title = element_text(hjust = 0.5, face = "bold", size = title_size),
      legend.position = "bottom",
      legend.key.width = unit(legend_key_width_cm, "cm"),
      legend.key.height = unit(0.3, "cm"),
      legend.title = element_text(size = 8),
      legend.text = element_text(size = 7)
    )

  # Save this panel standalone at native raster resolution (1 raster cell =
  # 1 output pixel, no up/downsampling) so any single service can be zoomed
  # into at full detail -- the combined figure below is an overview, not
  # meant for pixel-level inspection.
  panel_path <- file.path(panels_dir, paste0(tolower(service_name), "_", metric, ".png"))
  ggsave(panel_path, p, width = panel_width_in, height = panel_height_in + 1.2, dpi = panel_dpi, bg = "white", limitsize = FALSE)

  p
}

# ------------------------------------------------------------------------------
# 5. Build the paired-row figure for a given metric (pct or abs)
# ------------------------------------------------------------------------------

build_figure <- function(metric) {
  col_field <- if (metric == "pct") "col_pct" else "col_abs"
  message("Building ", metric, " figure...")

  panels <- list()
  for (d in panel_defs) {
    message("  -> ", d$service)
    panels[[d$service]] <- make_panel(d[[col_field]], d$service, metric)
  }

  rows <- lapply(row_pairs, function(pair) {
    left <- panels[[pair[1]]]
    if (is.na(pair[2])) {
      left | plot_spacer()
    } else {
      left | panels[[pair[2]]]
    }
  })

  combined <- Reduce(`/`, rows) +
    plot_annotation(
      title = "Ecosystem Service Change, 1992-2020 (10km-native grid)",
      subtitle = if (metric == "pct") "Percentage Change (%)" else "Absolute Change",
      theme = theme(plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
                    plot.subtitle = element_text(size = 14, hjust = 0.5))
    )

  # Overview composite only -- bumped from the first pass (12x22@300dpi) but
  # still well below the panels' native per-cell resolution at this page
  # size. For pixel-level zoom on any one service, use the standalone panel
  # PNGs in outputs/maps/native10km_panels/ instead (native raster resolution).
  out_path <- file.path(out_dir, paste0("map_native10km_", metric, ".png"))
  ggsave(out_path, combined, width = 20, height = 29, bg = "white", dpi = 300, limitsize = FALSE)
  message("Saved: ", out_path)
}

build_figure("pct")
build_figure("abs")

message("\nDone. Standalone per-service panels (native 10km-pixel resolution, basemap included)")
message("saved to outputs/maps/native10km_panels/ for zooming into any one service.")
message("NOTE: not yet referenced from paper_draft.qmd or the book chapters --")
message("map_biome_{pct,abs}.png (dissolved-by-biome) is untouched and still what those")
message("documents currently embed. Swapping the reference is a pending paper edit.")
