---
title: "R Notebook"
output: html_notebook
---




## **5. Compute Differences**


##### NOT RUN #######


```{r get differences, eval=FALSE, include=FALSE}
outpath <- here("input_ES")
m_index <- length(rasters_list) %/% 2
lab <- unique(service)
lab <- gsub(" ", "_", lab)


l1 <- rasters_list[seq(1,length(rasters_list), by=2)]
l2 <- rasters_list[seq(2,length(rasters_list), by=2)]
 # test with future_map2 next time to get this to run faster. 

diffs <- map2(l2, l1, ~ .x - .y)

# Export difference rasters
map(1:length(diffs), function(x) writeRaster(diffs[[x]], paste0(outpath, "/change_calc/", lab[x], '_diff.tif'),overwrite=TRUE))
```


### 6.1  Prepare Potential of Sed retention data.

```{r getpotential Sed retention , eval=FALSE, include=FALSE}
inpath <- here("input_ES", "Pot_Sed_retention")
tiffes <- file.path(inpath, list.files(paste0(inpath),pattern= 'tif$'))
filename<- basename(tiffes)
# Use terra::rast() to load each file as a SpatRaster object


rasters_list <- lapply(tiffes, rast)
rcl <- matrix(c(
  -Inf, 0, NA   # Any value from 0 to Infinity becomes 1
), ncol = 3, byrow = TRUE)

rasters_list <- lapply(rasters_list, function(r){
  r <- classify(r,rcl, right=FALSE)
})

m_index <- length(rasters_list) %/% 2
#lab <- unique(service)
l1 <- rasters_list[seq(1,length(rasters_list), by=2)]
l2 <- rasters_list[seq(2,length(rasters_list), by=2)]
 # test with future_map2 next time to get this to run faster. 

pot_SedRet1 <- (l1[[2]]-l1[[1]])/l1[[2]]


pot_SedRet2 <- (l2[[2]]-l2[[1]])/l2[[2]]

psr_92 <- classify(pot_SedRet1,rcl, right=FALSE)
psr_20 <- classify(pot_SedRet2,rcl, right=FALSE)

writeRaster(psr_92, paste0(inpath, '/', 'pot_SedRet_92.tif'), overwrite=TRUE)
writeRaster(psr_20, paste0(inpath, '/', 'pot_SedRet_20.tif'), overwrite=TRUE)
diff <- psr_92 - psr_20
writeRaster(diff, paste0(inpath, '/', 'pot_Sed_r_diff.tif'), overwrite)

```


## 8. Calculte export potential

```{r get retention potential per year}

inpath <- here('Input_ES', 'mode_set_ret')


#load the rasters with the calculated differences 
tiffes <- file.path(inpath, list.files(paste0(inpath),pattern= 'tif$'))
filename<- basename(tiffes)
cd

rast_list <- lapply(tiffes, rast)

# year <- c(1992,1995,1998,2001,2004)
# 
# pot_s_loss <- Map(function(r1,r2) r2/(r2-r1), rast_list1, rast_list2)
# 
# map(1:length(pot_s_loss), function(x) writeRaster(pot_s_loss[[x]], paste0(inpath, '/', 'pot_s_loss_', year[x],'.tif')))


```


Produce Change maps



```{r load data}

inpsath <- '/home/jeronimo/OneDrive/Global_ES_mapping/ESA_LC'
tiffes <- file.path(inpath, list.files(paste0(inpath),pattern= 'tif$'))
filename<- basename(tiffes)
#set <- 'continent.gpkg' 

raster_list <- lapply(rast,fiffes)

poly <- st_read(here('vector', set)) 

poly <- poly %>% filter(continent=='South America')


raster_list <- lapply(raster_list, function(r){
  r <- crop(r,poly)
  r <- mask(r,poly)
}

n_ch_sa <- noch_msk(raster_list, type='nochange')




poly <- 
# Use terra::rast() to load each file as a SpatRaster object





```