---
title: "Data preparation"
output: html_notebook
---
```{r setup, message=FALSE, warning=FALSE}
library(terra)
library(sf)
library(dplyr)
library(ggplot2)
library(glue)
library(tidyr)
library(purrr)
library(diffeR)
library(here)
library(stringr)
library(tidytext)
library(rlang)
library(tidyr)
library(forcats)
library(scales)
library(RColorBrewer)
library(htmltools)
library(leaflet)
library(devtools)
library(foreign)
load_all()
```

I should set this up to call the packages when loading as a normal package


# Mask the dataset with the farmsize

```{r mask Lesiv et al crop size}
inpath <- '/Users/rodriguez/Library/CloudStorage/OneDrive-WorldWildlifeFund,Inc/global_NCP/data/analysis/Global_Field_Sizes'
cs <- rast(paste(inpath, 'dominant_field_size_categories.tif', sep = "/")) 
vat <- read.dbf(paste(inpath, 'dominant_field_size_categories.tif.vat.dbf', sep = "/"))
head(vat) # tio check the values
msk <- st_read('/Users/rodriguez/Library/CloudStorage/OneDrive-WorldWildlifeFund,Inc/global_NCP/data/vector/hydrosheds_lv6_synth.gpkg')

cs <- mask(cs, msk)
plot(cs)
writeRaster(cs, '/Users/rodriguez/Library/CloudStorage/OneDrive-WorldWildlifeFund,Inc/global_NCP/data/analysis/Global_Field_Sizes/dom_fs_cat_mskd.tif')

mehrabi <- rast('/Users/rodriguez/OneDrive - World Wildlife Fund, Inc/global_NCP/data/analysis/Mehrabi/SI_A/Data/Out/farmsize.tif')

mehrabi <- crop(mehrabi,cs)

mehraby <- resample(mehrabi, cs)

rcl <- matrix(c(
  0, Inf, 1   # Any value greater than 0 becomes 1
), ncol = 3, byrow = TRUE)
mehraby <- classify(mehraby,rcl)

cs <- mask(cs,mehraby)

writeRaster(cs, '/Users/rodriguez/Library/CloudStorage/OneDrive-WorldWildlifeFund,Inc/global_NCP/data/analysis/Global_Field_Sizes/dom_fs_cat_mskd2.tif')

```



# 2. Get 