---
title: "Current Status"
output: html_notebook
---
  
# 1. Create Pollination Mask


```{r pollination, eval=FALSE, include=FALSE}
# I will have to update the paths here!!! (on it)
po_c <- rast('/Users/rodriguez/Library/CloudStorage/OneDrive-WorldWildlifeFund,Inc/global_NCP/data/Spring/Change/ndv_0.0_realized_pollination_on_ag_marESA_2020-1992_fullchange_md5_8e63e2.tif')

outpath <- '/Users/rodriguez/Library/CloudStorage/OneDrive-WorldWildlifeFund,Inc/global_NCP/data/Spring/Change'
# Reclassification matrix
# Format: from, to, becomes
rcl <- matrix(c(
  -Inf, -0.09, 0,
  -0.09, Inf, 1
), ncol = 3, byrow = TRUE)

msk_po_c <- classify(po_c,rcl)

po_c <- mask(po_c, msk_po_c, maskvalues=0)
writeRaster(po_c,paste0(outpath, '/', 'masked_ndv_0.0_realized_pollination_on_ag_marESA_2020-1992_fullchange_md5_8e63e2.tif'), overwrite =TRUE)
writeRaster(msk_po_c,paste0(outpath, '/', 'mask_pollination_change.tif'))


inpath <- '/Users/rodriguez/Library/CloudStorage/OneDrive-WorldWildlifeFund,Inc/global_NCP/data/Spring/Change' # maybe remove. I don't remember what the purpose of this is right now. 
po_c <- rast(paste0(inpath, '/', 'masked_ndv_0.0_realized_pollination_on_ag_marESA_2020-1992_fullchange_md5_8e63e2.tif')

```

```{r ch_no_ch}
#2.  Clip The rasters by the Project Areas.

#Example file paths (replace with actual paths)
inpath <- '/Users/rodriguez/Library/CloudStorage/OneDrive-WorldWildlifeFund,Inc/global_NCP/data/input_rasters/LandCovers'
landcover_files <- list.files(
  inpath,
  pattern = "rec.*\\.tif$", 
  full.names = TRUE
)
# Select the ESA Classifications to process. In this case 1992 (first available), 1995, 2000, 2005, 2010, 2015, 2020) 
# I am using these yearsd because the other global datasets I am evaluating (gridded HDI, gridded GDP, )
landcover_files <- landcover_files[c(1,12)]

# Name rasters by year
names(landcover_files) <- stringr::str_extract(basename(landcover_files), "\\d{4}")
# Load rasters as a list. (I think app() allows to iterate over the layers, but the output is a single synhesis band, not a dataframe, as we need here )
landcover_rasters <- lapply(landcover_files, terra::rast)
landcover_rasters <- c(landcover_rasters[[1]],landcover_rasters[[2]])
create_ch_msk <- no_chmsk(landcover_rasters, type = "change")

writeRaster(create_ch_msk, paste0(inpath, "no_ch_1992_2020.tif"))

```



# Access Change:


```{r access}
access_1992 <- rast('/Users/rodriguez/Downloads/nature_access_lspop2019_marESA1992_md5_b32b8b.tif')
rcl <- matrix(c(
  -Inf, Inf, 0), ncol = 3, byrow = TRUE)

acc_bkg <- classify(access_1992,rcl)

plot(acc_bkg)


access_2020 <- rast('/Users/rodriguez/Downloads/nature_access_lspop2019_ESA2020_compressed_md5_6727ac.tif')
access_2020<- merge(access_2020, acc_bkg)

writeRaster(access_2020, '/Users/rodriguez/Downloads/nature_access_lspop2019_ESA2020_compressed_md5_6727ac_bkg.tif')
plot(access_2020)

access_diff <- access_2020-access_1992
writeRaster(access_diff, '/Users/rodriguez/Downloads/nature_access_lspop2019_ESA_1992_2020_diff.tif')

```
```{r check access}


poly1 <- st_read('/Users/rodriguez/Library/CloudStorage/OneDrive-WorldWildlifeFund,Inc/global_NCP/output_data/10k_grid_access_synth_zonal_2025_07_28_23_37_52.gpkg')


head(poly1)

poly1 <- poly1 %>% mutate(diff_calc = (nature_access_lspop2019_ESA2020._mean - nature_access_lspop2019_ESA1992_mean))
head(poly1)

st_write(poly1, '/Users/rodriguez/Library/CloudStorage/OneDrive-WorldWildlifeFund,Inc/global_NCP/output_data/10k_grid_access_synth_zonal_2025_07_28_23_37_52.gpkg', append = FALSE)
```

# Add the Access Daqta 

```{r access_data}


poly1. <- poly1

poly1$diff_calc <- NULL

poly1 <- poly1 %>%
  mutate(
    access_abs_chg = nature_access_lspop2019_ESA2020._mean - nature_access_lspop2019_ESA1992_mean,
    access_pct_chg = ifelse(
      nature_access_lspop2019_ESA1992_mean == 0,
      NA,
      ((nature_access_lspop2019_ESA2020._mean - nature_access_lspop2019_ESA1992_mean) /
       nature_access_lspop2019_ESA1992_mean) * 100
    )
  )

poly1
sf_acc <- compute_cNULLsf_acc <- compute_change(poly1, suffix = c("_sum", "_mean"), change_type= "both", drop_columns = FALSE)
st_write(poly1, '/Users/rodriguez/Library/CloudStorage/OneDrive-WorldWildlifeFund,Inc/global_NCP/output_data/10k_grid_access.gpkg', append = FALSE)
```