#' Compare R and Python Bitemporal Change Calculations
#'
#' This function loads the GPKG generated by the R pipeline and the Python pipeline
#' and compares them column by column to ensure the bi-temporal math is identical.
#'
#' @param r_gpkg_path Path to the R generated GPKG (e.g. "10k_change_calc.gpkg")
#' @param py_gpkg_path Path to the Python generated GPKG
#' @export
compare_methods <- function(r_gpkg_path, py_gpkg_path) {
  message("Loading R GPKG: ", r_gpkg_path)
  r_data <- sf::st_read(r_gpkg_path, quiet = TRUE) %>% sf::st_drop_geometry()

  message("Loading Python GPKG: ", py_gpkg_path)
  py_data <- sf::st_read(py_gpkg_path, quiet = TRUE) %>% sf::st_drop_geometry()

  # Safety fallback: sf sometimes drops primary keys like 'fid' from the attributes
  if (!"fid" %in% names(r_data)) r_data$fid <- seq_len(nrow(r_data))
  if (!"fid" %in% names(py_data)) py_data$fid <- seq_len(nrow(py_data))

  change_cols_R <- grep("(_abs_chg$|_pct_chg$)", names(r_data), value = TRUE)
  change_cols_Py <- grep("(_abs_chg$|_pct_chg$)", names(py_data), value = TRUE)

  change_cols <- intersect(change_cols_R, change_cols_Py)
  message("Comparing ", length(change_cols), " change columns...\n")

  if (length(change_cols) == 0) {
    stop("No matching change columns found! Check column renaming logic.")
  }

  comparison <- r_data %>%
    dplyr::select(fid, dplyr::all_of(change_cols)) %>%
    dplyr::inner_join(
      py_data %>% dplyr::select(fid, dplyr::any_of(change_cols)),
      by = "fid",
      suffix = c("_R", "_Py")
    )

  max_diffs <- numeric(length(change_cols))
  names(max_diffs) <- change_cols

  for (col in change_cols) {
    col_R <- paste0(col, "_R")
    col_Py <- paste0(col, "_Py")
    # Rounded to 5 decimal places to ignore floating point storage differences between R & SQLite
    diff_val <- max(abs(round(comparison[[col_R]], 5) - round(comparison[[col_Py]], 5)), na.rm = TRUE)
    max_diffs[col] <- diff_val
  }

  print(max_diffs)

  if (all(max_diffs == 0, na.rm = TRUE)) {
    message("\nSUCCESS: Both methods produced identical mathematical results!")
  } else {
    message("\nWARNING: Differences found between methods.")
  }
}